/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as challenge1 from "./Challenge1";
export type { challenge1 };
import type * as tokenErc20Drop from "./Token ERC20 Drop";
export type { tokenErc20Drop };
export type { Lock } from "./Lock";
