/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChallenge,
  IChallengeInterface,
} from "../../../Challenge1/Challenge1.sol/IChallenge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    name: "exploit_me",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lock_me",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IChallenge__factory {
  static readonly abi = _abi;
  static createInterface(): IChallengeInterface {
    return new Interface(_abi) as IChallengeInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IChallenge {
    return new Contract(address, _abi, runner) as unknown as IChallenge;
  }
}
