/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IChallengeInterface extends Interface {
  getFunction(nameOrSignature: "exploit_me" | "lock_me"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "exploit_me",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "lock_me", values?: undefined): string;

  decodeFunctionResult(functionFragment: "exploit_me", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lock_me", data: BytesLike): Result;
}

export interface IChallenge extends BaseContract {
  connect(runner?: ContractRunner | null): IChallenge;
  waitForDeployment(): Promise<this>;

  interface: IChallengeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  exploit_me: TypedContractMethod<[winner: AddressLike], [void], "nonpayable">;

  lock_me: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "exploit_me"
  ): TypedContractMethod<[winner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lock_me"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
