/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Challenge } from "./Challenge";
export type { Hacker } from "./Hacker";
export type { IChallenge } from "./IChallenge";
