/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dropBatchWithActiveTransfSol from "./DropBatch WithActiveTransf.sol";
export type { dropBatchWithActiveTransfSol };
export type { DropBatch } from "./DropBatch";
export type { DropOneInHand } from "./DropOneInHand";
export type { TokenERC20 } from "./TokenERC20";
