/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dropSol from "./Drop.sol";
export type { dropSol };
import type * as dropBatchWithActiveTransfSol from "./DropBatch WithActiveTransf.sol";
export type { dropBatchWithActiveTransfSol };
import type * as tokerErc20Sol from "./TokerERC20.sol";
export type { tokerErc20Sol };
export type { DropBatch } from "./DropBatch";
